lib/timesheet_web/router.ex
defmodule TimesheetWeb.Router do
  use TimesheetWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug TimesheetWeb.Plugs.FetchCurrentManager
    plug TimesheetWeb.Plugs.FetchCurrentWorker
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TimesheetWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/tasks/checkstatus", TaskController, :timesheetStatus
    resources "/managers", ManagerController,
    only: [:index]
    resources "/workers", WorkerController,
    only: [:index]
    resources "/sessionmanager", SessionmanagerController, 
    only: [:new, :create, :delete], singleton: true
    resources "/sessionworker", SessionworkerController, 
    only: [:new, :create, :delete], singleton: true
    resources "/jobs", JobController,
    only: [:index, :new, :create]
    resources "/tasks", TaskController
  end

  # Other scopes may use custom stacks.
  # scope "/api", TimesheetWeb do
  #   pipe_through :api
  # end
end

lib/timesheet/workers.ex
defmodule Timesheet.Workers do
  @moduledoc """
  The Workers context.
  """

  import Ecto.Query, warn: false
  alias Timesheet.Repo

  alias Timesheet.Workers.Worker

  @doc """
  Returns the list of workers.

  ## Examples

      iex> list_workers()
      [%Worker{}, ...]

  """
  def list_workers do
    Repo.all(Worker)
  end

  @doc """
  Gets a single worker.

  Raises `Ecto.NoResultsError` if the Worker does not exist.

  ## Examples

      iex> get_worker!(123)
      %Worker{}

      iex> get_worker!(456)
      ** (Ecto.NoResultsError)

  """
  def get_worker!(id), do: Repo.get!(Worker, id)

  def get_worker_by_email(email) do
    Repo.get_by!(Worker, email: email)
  end

  def get_worker(id), do: Repo.get(Worker, id)

  def authenticate(email, pass) do
    user = Repo.get_by(Worker, email: email)
    case Argon2.check_pass(user, pass) do
      {:ok, user} -> user
      _ -> nil
    end
  end  

  @doc """
  Creates a worker.

  ## Examples

      iex> create_worker(%{field: value})
      {:ok, %Worker{}}

      iex> create_worker(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """


  @doc """
  Updates a worker.

  ## Examples

      iex> update_worker(worker, %{field: new_value})
      {:ok, %Worker{}}

      iex> update_worker(worker, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  

  @doc """
  Deletes a Worker.

  ## Examples

      iex> delete_worker(worker)
      {:ok, %Worker{}}

      iex> delete_worker(worker)
      {:error, %Ecto.Changeset{}}

  """
  

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking worker changes.

  ## Examples

      iex> change_worker(worker)
      %Ecto.Changeset{source: %Worker{}}

  """
  def change_worker(%Worker{} = worker) do
    Worker.changeset(worker, %{})
  end

  alias Timesheet.Workers.Worker

  @doc """
  Returns the list of workers.

  ## Examples

      iex> list_workers()
      [%Worker{}, ...]

  """
  def list_workers do
    Repo.all(Worker)
  end

  def list_manager_id(id) do
    query = from u in "workers",
            where: u.manager_id == ^id,
            select: u.manager_id
            
    Repo.all(query)        
  end

  @doc """
  Gets a single worker.

  Raises `Ecto.NoResultsError` if the Worker does not exist.

  ## Examples

      iex> get_worker!(123)
      %Worker{}

      iex> get_worker!(456)
      ** (Ecto.NoResultsError)

  """
  def get_worker!(id), do: Repo.get!(Worker, id)

  @doc """
  Creates a worker.

  ## Examples

      iex> create_worker(%{field: value})
      {:ok, %Worker{}}

      iex> create_worker(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_worker(attrs \\ %{}) do
    %Worker{}
    |> Worker.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a worker.

  ## Examples

      iex> update_worker(worker, %{field: new_value})
      {:ok, %Worker{}}

      iex> update_worker(worker, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_worker(%Worker{} = worker, attrs) do
    worker
    |> Worker.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Worker.

  ## Examples

      iex> delete_worker(worker)
      {:ok, %Worker{}}

      iex> delete_worker(worker)
      {:error, %Ecto.Changeset{}}

  """
  def delete_worker(%Worker{} = worker) do
    Repo.delete(worker)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking worker changes.

  ## Examples

      iex> change_worker(worker)
      %Ecto.Changeset{source: %Worker{}}

  """
  def change_worker(%Worker{} = worker) do
    Worker.changeset(worker, %{})
  end
end

lib/timesheet/workers/worker.ex
defmodule Timesheet.Workers.Worker do
  use Ecto.Schema
  import Ecto.Changeset

  schema "workers" do
    field :email, :string
    field :name, :string
    field :password_hash, :string
    field :manager_id, :id

    timestamps()
  end

  @doc false
  def changeset(worker, attrs) do
    worker
    |> cast(attrs, [:email, :name, :password_hash])
    |> validate_required([:email, :name, :password_hash])
  end
end

lib/timesheet_web/controllers/worker_controller.ex
defmodule TimesheetWeb.WorkerController do
  use TimesheetWeb, :controller

  alias Timesheet.Workers
  alias Timesheet.Workers.Worker

  def index(conn, _params) do
    workers = Workers.list_workers()
    render(conn, "index.html", workers: workers)
  end

  def new(conn, _params) do
    changeset = Workers.change_worker(%Worker{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"worker" => worker_params}) do
    case Workers.create_worker(worker_params) do
      {:ok, worker} ->
        conn
        |> put_flash(:info, "Worker created successfully.")
        |> redirect(to: Routes.worker_path(conn, :show, worker))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    worker = Workers.get_worker!(id)
    render(conn, "show.html", worker: worker)
  end

  def edit(conn, %{"id" => id}) do
    worker = Workers.get_worker!(id)
    changeset = Workers.change_worker(worker)
    render(conn, "edit.html", worker: worker, changeset: changeset)
  end

  def update(conn, %{"id" => id, "worker" => worker_params}) do
    worker = Workers.get_worker!(id)

    case Workers.update_worker(worker, worker_params) do
      {:ok, worker} ->
        conn
        |> put_flash(:info, "Worker updated successfully.")
        |> redirect(to: Routes.worker_path(conn, :show, worker))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", worker: worker, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    worker = Workers.get_worker!(id)
    {:ok, _worker} = Workers.delete_worker(worker)

    conn
    |> put_flash(:info, "Worker deleted successfully.")
    |> redirect(to: Routes.worker_path(conn, :index))
  end
end

lib/timesheet_web/views/worker_view.ex
defmodule TimesheetWeb.WorkerView do
  use TimesheetWeb, :view
end

lib/timesheet_web/templates/worker/edit.html.eex
<h1>Edit Worker</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.worker_path(@conn, :update, @worker)) %>

<span><%= link "Back", to: Routes.worker_path(@conn, :index) %></span>

lib/timesheet_web/templates/worker/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :email %>
  <%= text_input f, :email %>
  <%= error_tag f, :email %>

  <%= label f, :name %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>

  <%= label f, :password_hash %>
  <%= text_input f, :password_hash %>
  <%= error_tag f, :password_hash %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/timesheet_web/templates/worker/index.html.eex
<h1>Listing Workers</h1>
(<span><%= link("Sign Out", to: Routes.sessionworker_path(@conn, :delete),
              method: :delete) %>)</span>
              
<h2>View Available Jobs</h2>

<span><%= link "View Jobs", to: Routes.job_path(@conn, :index) %></span>


<h2>Submit Timesheets for the Employees</h2>

<span><%= link "Submit Timesheets", to: Routes.task_path(@conn, :new) %></span>


<h2>Check Timesheets  Status </h2>
<span><%= link "Check Timesheet Status", to: Routes.task_path(@conn, :timesheetStatus) %></span>

lib/timesheet_web/templates/worker/new.html.eex
<h1>New Worker</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.worker_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.worker_path(@conn, :index) %></span>

lib/timesheet_web/templates/worker/show.html.eex
<h1>Show Worker</h1>

<ul>

  <li>
    <strong>Email:</strong>
    <%= @worker.email %>
  </li>

  <li>
    <strong>Name:</strong>
    <%= @worker.name %>
  </li>

  <li>
    <strong>Password hash:</strong>
    <%= @worker.password_hash %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.worker_path(@conn, :edit, @worker) %></span>
<span><%= link "Back", to: Routes.worker_path(@conn, :index) %></span>