lib/timesheet_web/router.ex
defmodule TimesheetWeb.Router do
  use TimesheetWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug TimesheetWeb.Plugs.FetchCurrentManager
    plug TimesheetWeb.Plugs.FetchCurrentWorker
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TimesheetWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/tasks/checkstatus", TaskController, :timesheetStatus
    resources "/managers", ManagerController,
    only: [:index]
    resources "/workers", WorkerController,
    only: [:index]
    resources "/sessionmanager", SessionmanagerController, 
    only: [:new, :create, :delete], singleton: true
    resources "/sessionworker", SessionworkerController, 
    only: [:new, :create, :delete], singleton: true
    resources "/jobs", JobController,
    only: [:index, :new, :create]
    resources "/tasks", TaskController
  end

  # Other scopes may use custom stacks.
  # scope "/api", TimesheetWeb do
  #   pipe_through :api
  # end
end

lib/timesheet/tasks.ex
defmodule Timesheet.Tasks do
  @moduledoc """
  The Tasks context.
  """

  import Ecto.Query, warn: false
  alias Timesheet.Repo

  alias Timesheet.Tasks.Task

  @doc """
  Returns the list of tasks.

  ## Examples

      iex> list_tasks()
      [%Task{}, ...]

  """
  def list_tasks do
    Repo.all(Task)
  end

  @doc """
  Gets a single task.

  Raises `Ecto.NoResultsError` if the Task does not exist.

  ## Examples

      iex> get_task!(123)
      %Task{}

      iex> get_task!(456)
      ** (Ecto.NoResultsError)

  """
  def get_task!(id), do: Repo.get!(Task, id)

  @doc """
  Creates a task.

  ## Examples

      iex> create_task(%{field: value})
      {:ok, %Task{}}

      iex> create_task(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_task(attrs \\ %{}) do

    total = calculateHours(attrs)
    IO.inspect(total)
    if total > 8 || total < 1 do
      map = %{"job_id" => attrs["job_id"], "hours" => total, "note" => attrs["note"], "worker_id" => attrs["worker_id"]}
      IO.inspect(map)
      %Task{}
      |> Task.changeset(map)
      |> Repo.insert()
    else
      insertNonEmptyRows(attrs)
    end
  end


  def insertNonEmptyRows(attrs) do
    hours = attrs["hours"]
    hours = returnInteger(hours)

   if hours > 0 do
   end 
   insertRows(attrs, 1)
  end

  def insertRows(attrs, index) when index <= 7 do
    newIndex = index
    newIndex = Integer.to_string(newIndex)
    job = "job_id" <> newIndex
    hour = "hours" <> newIndex
    IO.inspect("inside insert row method")
    IO.inspect(job)
    job1 = attrs[job]
    hours1 = attrs[hour]
    IO.inspect(job1)

    getHours = returnInteger(hours1)
    if getHours > 0 do
      map = %{"job_id" => job1, "hours" => hours1, "note" => attrs["note"], "worker_id" => attrs["worker_id"]}
      %Task{}
      |> Task.changeset(map)
      |> Repo.insert()
      insertRows(attrs, index + 1)
    else 
      insertRows(attrs, index + 1)
    end
    
  end

  def insertRows(attrs, index) when index > 7 do
    %Task{}
    |> Task.changeset(attrs)
    |> Repo.insert()
  end


  def calculateHours(inputMap) do
    totalHours = 0
    job = inputMap["hours"]
    job = returnInteger(job)
    job1 = inputMap["hours1"]
    job1 = returnInteger(job1)
    job2 = inputMap["hours2"]
    job2 = returnInteger(job2)
    job3 = inputMap["hours3"]
    job3 = returnInteger(job3)
    job4 = inputMap["hours4"]
    job4 = returnInteger(job4)
    job5 = inputMap["hours5"]
    job5 = returnInteger(job5)
    job6 = inputMap["hours6"]
    job6 = returnInteger(job6)
    job7 = inputMap["hours7"]
    job7 = returnInteger(job7)
 
    totalHours = job + job1 + job2 + job3 + job4 + job5 + job6 + job7
  end



  def returnInteger(job) do
    if job != "" do
      {a,_} = Integer.parse(job)
      a
    else 
      0  
    end
  end
  @doc """
  Updates a task.

  ## Examples

      iex> update_task(task, %{field: new_value})
      {:ok, %Task{}}

      iex> update_task(task, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_task(%Task{} = task, attrs) do
    
    task
    |> Task.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Task.

  ## Examples

      iex> delete_task(task)
      {:ok, %Task{}}

      iex> delete_task(task)
      {:error, %Ecto.Changeset{}}

  """
  def delete_task(%Task{} = task) do
    Repo.delete(task)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking task changes.

  ## Examples

      iex> change_task(task)
      %Ecto.Changeset{source: %Task{}}

  """
  def change_task(%Task{} = task) do
    Task.changeset(task, %{})
  end
end

lib/timesheet/tasks/task.ex
defmodule Timesheet.Tasks.Task do
  use Ecto.Schema
  import Ecto.Changeset

  schema "tasks" do
    field :approved, :boolean, default: false
    field :hours, :integer
    field :job_id, :string
    field :note, :string
    field :worker_id, :integer

    timestamps()
  end

  @doc false
  def changeset(task, attrs) do
    task
    |> cast(attrs, [:worker_id, :job_id, :hours, :note, :approved])
    |> validate_required([:job_id, :hours])
    |> validate_inclusion(:hours, 1..8)
  end
end

lib/timesheet_web/controllers/task_controller.ex
defmodule TimesheetWeb.TaskController do
  use TimesheetWeb, :controller

  alias Timesheet.Tasks
  alias Timesheet.Tasks.Task
  alias Timesheet.Workers
  alias Timesheet.Workers.Worker

  def index(conn, _params) do
    tasks = Tasks.list_tasks()
    workers = Workers.list_manager_id(conn.assigns[:current_user].id)
    render(conn, "index.html", tasks: tasks, workers: workers)
  end

  def timesheetStatus(conn, _params) do
    tasks = Tasks.list_tasks()
    render(conn, "timesheetStatus.html", tasks: tasks)
  end

  def new(conn, _params) do
    changeset = Tasks.change_task(%Task{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"task" => task_params}) do
    IO.inspect(conn.assigns[:current_user])
    task_params = Map.put(task_params, "worker_id", conn.assigns[:current_user].id)
    IO.inspect(task_params)
    case Tasks.create_task(task_params) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task created successfully.")
        |> redirect(to: Routes.task_path(conn, :new))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    task = Tasks.get_task!(id)
    render(conn, "show.html", task: task)
  end

  def edit(conn, %{"id" => id}) do
    task = Tasks.get_task!(id)
    changeset = Tasks.change_task(task)
    render(conn, "edit.html", task: task, changeset: changeset)
  end

  def update(conn, %{"id" => id, "task" => task_params}) do
    task = Tasks.get_task!(id)
    IO.inspect("inside task update")
    task_params = Map.put(task_params, "approved", :true)
    IO.inspect(task_params)
    case Tasks.update_task(task, task_params) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task updated successfully.")
        |> redirect(to: Routes.task_path(conn, :show, task))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", task: task, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    task = Tasks.get_task!(id)
    {:ok, _task} = Tasks.delete_task(task)

    conn
    |> put_flash(:info, "Task deleted successfully.")
    |> redirect(to: Routes.task_path(conn, :index))
  end
end

lib/timesheet_web/views/task_view.ex
defmodule TimesheetWeb.TaskView do
  use TimesheetWeb, :view
end

lib/timesheet_web/templates/task/edit.html.eex
<h2>Approve Task</h2> <span><%= link "Back", to: Routes.task_path(@conn, :index) %></span>

<%= render "form.html", Map.put(assigns, :action, Routes.task_path(@conn, :update, @task)) %>

lib/timesheet_web/templates/task/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>


<table class="table table-dark table-bordered">
  <thead>
    <tr>
      <th>Job</th>
      <th>Hours</th>
    </tr>
  </thead>
  <tbody>
  <tr>
  <td>
      <%= text_input f, :job_id, class: "form-control"%>
  </td>
  <td>
       <%= number_input f, :hours, class: "form-control" %>
  </td>
  </tr>
  <tr>
    <td>
      <%= text_input f, :job_id1, class: "form-control"%>
  </td>
  <td>
       <%= number_input f, :hours1, class: "form-control" %>
  </td>
  </tr>
    <tr>
  <td>
      <%= text_input f, :job_id2, class: "form-control"%>
  </td>
  <td>
       <%= number_input f, :hours2, class: "form-control" %>
  </td>
  </tr>
  <tr>
    <td>
      <%= text_input f, :job_id3, class: "form-control"%>
  </td>
  <td>
       <%= number_input f, :hours3, class: "form-control" %>
  </td>
  </tr>
    <tr>
  <td>
      <%= text_input f, :job_id4, class: "form-control"%>
  </td>
  <td>
       <%= number_input f, :hours4, class: "form-control" %>
  </td>
  </tr>
  <tr>
    <td>
      <%= text_input f, :job_id5, class: "form-control"%>
  </td>
  <td>
       <%= number_input f, :hours5, class: "form-control" %>
  </td>
  </tr>
    <tr>
  <td>
      <%= text_input f, :job_id6, class: "form-control"%>
  </td>
  <td>
       <%= number_input f, :hours6, class: "form-control" %>
  </td>
  </tr>
  <tr>
    <td>
      <%= text_input f, :job_id7, class: "form-control"%>
  </td>
  <td>
       <%= number_input f, :hours7, class: "form-control" %>
  </td>
  </tr>
  </tbody>
 </table> 

  <div class = "form-group">
     <%= label f, :note, class: "label-primary"  %>
     <%= text_input f, :note, class: "form-control"  %>
     <%= error_tag f, :note %>
  </div>  

  <div class = "form-group">
    <%= submit "Save", class: "btn btn-primary"%>
  </div>
<% end %>

lib/timesheet_web/templates/task/index.html.eex
<h2> Approve Timesheets </h2> <span><%= link "My Home", to: Routes.manager_path(@conn, :index) %>
</span> (<span><%= link("Sign Out", to: Routes.sessionmanager_path(@conn, :delete),
              method: :delete) %>)</span>

<table class="table table-dark">
  <thead>
    <tr>
      
      <th>Job</th>
      <th>Hours</th>
      <th>Worker ID</th>
      <th>Status </th>
      <th>Approval</th>
    </tr>
  </thead>
  <tbody>
<%= for task <- @tasks do %>
  <%= if Enum.member?(@workers, task.worker_id) do %>
    <tr>
      
      <td><%= task.job_id %></td>
      <td><%= task.hours %></td>
      <td><%= task.worker_id  %></td>
      <td><%= task.approved  %></td>
      <td><%= link "Approve", to: Routes.task_path(@conn, :edit,task.id) %></td>
   
    </tr>
  <% end %>  
<% end %>
  </tbody>
</table>

lib/timesheet_web/templates/task/new.html.eex
<h1>New Task</h1>

<span><%= link "Back", to: Routes.worker_path(@conn, :index) %></span>
<%= render "form.html", Map.put(assigns, :action, Routes.task_path(@conn, :create)) %>

lib/timesheet_web/templates/task/show.html.eex
<h1>Show Task</h1>


<table class="table table-dark">
  <thead>
    <tr>
      
      <th><strong>Worker</strong></th>
      <th> <strong>Job</strong></th>
      <th> <strong>Hours</strong></th>
      <th><strong>Note</strong></th>
      <th> <strong>Approved</strong></th>
    </tr>
  </thead>
  <tbody>

    <tr>
      
      <td><%= @task.worker_id %></td>
      <td><%= @task.job_id %></td>
      <td><%= @task.hours %></td>
      <td><%= @task.note %></td>
      <td><%= @task.approved %></td>
   
    </tr>

  </tbody>
</table>




<span><%= link "Have Changes?", to: Routes.task_path(@conn, :edit, @task) %></span>
<span><%= link "Go to Approve Timesheets", to: Routes.task_path(@conn, :index) %></span>

lib/timesheet_web/templates/task/timesheetStatus.html.eex
<h2>Timesheet Status</h2>
(<span><%= link("Sign Out", to: Routes.sessionworker_path(@conn, :delete),method: :delete) %>)</span>
              
<span><%= link "My Home", to: Routes.worker_path(@conn, :index) %></span>
<table class="table table-dark">
  <thead>
    <tr>
      
      <th>Job</th>
      <th>Hours</th>
      <th>Worker ID</th>
      <th>Status </th>
    </tr>
  </thead>
  <tbody>
<%= for task <- @tasks do %>
<%= if task.worker_id == @current_user.id do %>
    <tr>
      <td><%= task.job_id %></td>
      <td><%= task.hours %></td>
      <td><%= task.worker_id  %></td>
      <%= if task.approved == true do %>
         <td>Approved</td>
      <% else %>
         <td>Not Approved</td>
      <% end %>   
   
    </tr>
<% end %>    
<% end %>
  </tbody>
</table>